# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Joan M
tagline:          "@Barcelona"
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Joan Martínez
  url:            https://twitter.com/mdo
  email:          hello@pantry.cat

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
